version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    groups:
      python-governance-dependencies:
        patterns:
          - PyYAML
          - jsonschema

  - package-ecosystem: pip
    directory: /tests/browser
    schedule:
      interval: daily
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - actions/*
